go:
    version: 1.12
repository:
    path: github.com/lukasmalkmus/rpi_exporter
build:
    flags: -mod=vendor -buildmode=exe -tags=netgo -installsuffix=cgo -a
    ldflags: |
        -s
        -w
        -extldflags="-static"
        -X={{repoPath}}/vendor/github.com/prometheus/common/version.Version={{.Version}}
        -X={{repoPath}}/vendor/github.com/prometheus/common/version.Revision={{.Revision}}
        -X={{repoPath}}/vendor/github.com/prometheus/common/version.Branch={{.Branch}}
        -X={{repoPath}}/vendor/github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X={{repoPath}}/vendor/github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
    gcflags:
        -trimpath=$(GOPATH)/src
    asmflags:
        -trimpath=$(GOPATH)/src
tarball:
    files:
        - LICENSE
        - NOTICE
        - systemd/rpi_exporter.service
crossbuild:
    platforms:
        - linux/arm
        - linux/arm64
