[metadata]
  project = "gortys"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"